### ISSUE TITLE
BUG FIXED: Calibration result seems to be wrong

### ISSUE THREAD

**Issue by KopiSoftware** [HenryWJL/hand_eye_calibration#1]
I'm currently use this project for calibration recently. It is found the calibration result went wrong sometimes. Then I fixed this bug and then modified this project to use `geometry_msgs.msg.Pose`.

1. The wrong results is due to mixed use of topic `\tf`. Changing the publishment and subscription could solve this problem.
``` python
# in hand_to_eye_calib.py
rospy.Subscriber('/tf2', TFMessage, target_pose_callback, queue_size=10)

# in checkerboard_detection.py
tf_pub = rospy.Publisher("/tf2", TFMessage, queue_size=10)
```

2. To adopt this project with Realman Arm, I changed the receiving part of `hand_to_eye_calib.py`.
```python
from geometry_msgs.msg import TwistStamped, Pose
rospy.Subscriber('/tf2', TFMessage, target_pose_callback, queue_size=10)
def get_end2base_mat(pose):
    # Calculating the gripper-to-base transformation matrix
    tran = np.array((pose.position.x, pose.position.y, pose.position.z))
    # rot = tfs.euler.euler2mat(pose.orientation.x, pose.orientation.y, pose.orientation.z)
    rot = tfs.quaternions.quat2mat([pose.orientation.w, pose.orientation.x, pose.orientation.y, pose.orientation.z])
    # invert
    # tran = -np.array(rot).T * tran
    # rot = np.array(rot).T
    return rot, tran
```
if anyone want to see my work, see [my branch](https://github.com/KopiSoftware/hand_eye_calibration).

**Comment by HenryWJL** [comment]
Thanks a lot! I have already modified "/tf" into "/tf2". If there are other bugs, please feel free to contact me.
